services:
  server:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
    networks:
      - backend

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_DB=macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "macbook" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: