services:
  ms-get:
    build:
      context: ./ms-get
      dockerfile: Dockerfile
    container_name: ms-get
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
    networks:
      - backend

  ms-post:
    build:
      context: ./ms-post
      dockerfile: Dockerfile
    container_name: ms-post
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
    networks:
      - backend


  ms-put:
    build:
      context: ./ms-put
      dockerfile: Dockerfile
    container_name: ms-put
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
    networks:
      - backend


  ms-delete:
    build:
      context: ./ms-delete
      dockerfile: Dockerfile
    container_name: ms-delete
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
    networks:
      - backend

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_DB=macbook
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=macbook
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "macbook" ]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    build:
      context: ./ms-api-gateway
      dockerfile: Dockerfile
    depends_on:
       - ms-get
       - ms-delete
       - ms-post
       - ms-put
    ports:
       - 80:8080
    networks:
       - backend
       - frontend
    environment:
       - SERVER=server
networks:
  backend:
  frontend:

volumes:
  db-data: